### ISSUE TITLE
The rendered images are different from the imput images a lot with the same camera parameters

### ISSUE THREAD

**Issue by Txusheng** [yuyingyeh/TransparentShapeRealData#1]
Hi

Thank you for releasing the code and the dataset.
I am testing the transparent object reconstruction based on the real dataset recently.

I tried to render the images (only background, no transparent object) based on the environment map with the given camera parameters, and it seems that the rendered images differ from the input images a lot. Here are the rendered images and input images:
![image](https://user-images.githubusercontent.com/17637838/103992988-dd6e3700-51cf-11eb-9837-b519642317fd.png)
![image](https://user-images.githubusercontent.com/17637838/103993003-e0692780-51cf-11eb-82a3-40ee9452917b.png)

Is this phenomenon right?
I use the codes for ray generation and environment map sampling provided by this project. Perhaps the quality of the environment map is not that ideal?

**Comment by yuyingyeh** [comment]
Thanks for your interest in our work. Unfortunately, the environment maps captured from mobile phone might contain a bit noise due to inaccurate camera poses. However, it is enough for our model to compute the rendered images from the reconstructed environment map and do the inference.
