### ISSUE TITLE
the number of output channels is wrong

### ISSUE THREAD

**Issue by s1752729916** [yuyingyeh/TransparentShapeRealData#3]
It should output 14 channels of data(as shown in `3_computeVisualHull.py`), but in fact, OptixRender only outputs 12 channels, which should be missing SEG_ VH1 and SEG_ VH2. I have checked all branches of OptixRender and found no code that can output 14 channels. Is there something wrong with me?  thank you

**Comment by yuyingyeh** [comment]
Hi @s1752729916 ! Thanks for your interest in our work. Could you try `transparentShape` branch? https://github.com/lzqsd/OptixRenderer/tree/transparentShape

**Comment by s1752729916** [comment]
> Hi @s1752729916 ! Thanks for your interest in our work. Could you try `transparentShape` branch? https://github.com/lzqsd/OptixRenderer/tree/transparentShape

Thank you for your reply. I am using the `transparentShape`  branch now, but this branch only outputs 12 channels. I solved this problem in another way because I can manually calculate their segmentation maps from the output data.

**Comment by 78ij** [comment]
Hi @s1752729916, I have encountered the exact same problem(OptixRenderer outputs only 12 channels with `transparentShape`, but 28 channels with `transparentHollow`, both do not have 14 channels). Do you mind sharing your solutions to this problem? Many thanks!
